#import "URLImportViewController.h"
@implementation URLImportViewController
@synthesize delegate=_delegate;
- (void)viewDidLoad{[super viewDidLoad];self.title=@"URL / FTP İndir";self.view.backgroundColor=[UIColor groupTableViewBackgroundColor];_field=[[UITextField alloc]initWithFrame:CGRectMake(30,40,self.view.bounds.size.width-60,40)];_field.borderStyle=UITextBorderStyleRoundedRect;_field.placeholder=@"http:// veya ftp:// ...pdf";_field.delegate=self;_field.autocapitalizationType=UITextAutocapitalizationTypeNone;[self.view addSubview:_field];UIButton*b=[UIButton buttonWithType:UIButtonTypeRoundedRect];b.frame=CGRectMake(30,95,160,44);[b setTitle:@"PDF İndir" forState:UIControlStateNormal];[b addTarget:self action:@selector(download) forControlEvents:UIControlEventTouchUpInside];[self.view addSubview:b];_status=[[UILabel alloc]initWithFrame:CGRectMake(30,150,self.view.bounds.size.width-60,80)];_status.numberOfLines=0;_status.backgroundColor=[UIColor clearColor];[self.view addSubview:_status];}
- (void)download{[_field resignFirstResponder];[_url release];_url=[[NSURL URLWithString:_field.text]retain];if(!_url){_status.text=@"Geçersiz URL";return;}[_data release];_data=[[NSMutableData alloc]init];NSURLRequest*r=[NSURLRequest requestWithURL:_url cachePolicy:NSURLRequestReloadIgnoringLocalCacheData timeoutInterval:60];[_conn release];_conn=[[NSURLConnection alloc]initWithRequest:r delegate:self startImmediately:YES];_status.text=@"İndiriliyor…";}
- (void)connection:(NSURLConnection*)c didReceiveData:(NSData*)d{[_data appendData:d];_status.text=[NSString stringWithFormat:@"İndiriliyor… %.1f KB",[_data length]/1024.0];}
- (void)connection:(NSURLConnection*)c didFailWithError:(NSError*)e{_status.text=[e localizedDescription];}
- (void)connectionDidFinishLoading:(NSURLConnection*)c{NSString*n=[[_url path]lastPathComponent];if(![[n pathExtension]length])n=@"download.pdf";NSString*docs=[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory,NSUserDomainMask,YES)objectAtIndex:0];NSString*p=[docs stringByAppendingPathComponent:n];if([_data writeToFile:p atomically:YES]){_status.text=@"İndirme tamamlandı.";if([_delegate respondsToSelector:@selector(urlImportFinishedAtPath:)])[_delegate urlImportFinishedAtPath:p];}else _status.text=@"Kaydedilemedi.";}
- (BOOL)textFieldShouldReturn:(UITextField*)t{[self download];return YES;}
- (void)dealloc{[_field release];[_status release];[_data release];[_conn cancel];[_conn release];[_url release];[super dealloc];}
@end
